# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Carla/LineCrossed.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
from SensorNearData import SensorStates_pb2 as SensorNearData_dot_SensorStates__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Carla/LineCrossed.proto',
  package='pb.Carla',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x17\x43\x61rla/LineCrossed.proto\x12\x08pb.Carla\x1a\x0cheader.proto\x1a!SensorNearData/SensorStates.proto\"\xc0\x02\n\x0bLineCrossed\x12\x1a\n\x06header\x18\x01 \x01(\x0b\x32\n.pb.Header\x12(\n\x04\x65rrs\x18\x03 \x01(\x0b\x32\x1a.pb.Carla.LineCrossed.Errs\x12.\n\x07signals\x18\x04 \x01(\x0b\x32\x1d.pb.Carla.LineCrossed.Signals\x12\x33\n\ntimestamps\x18\x06 \x01(\x0b\x32\x1f.pb.Carla.LineCrossed.Timestamp\x1a;\n\x04\x45rrs\x12\x33\n\x0cline_crossed\x18\x02 \x01(\x0e\x32\x10.pb.SensorStates:\x0bSTATE_FAULT\x1a&\n\x07Signals\x12\x1b\n\x0cline_crossed\x18\x03 \x01(\x08:\x05\x66\x61lse\x1a!\n\tTimestamp\x12\x14\n\x0cline_crossed\x18\x02 \x01(\x12'
  ,
  dependencies=[header__pb2.DESCRIPTOR,SensorNearData_dot_SensorStates__pb2.DESCRIPTOR,])




_LINECROSSED_ERRS = _descriptor.Descriptor(
  name='Errs',
  full_name='pb.Carla.LineCrossed.Errs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_crossed', full_name='pb.Carla.LineCrossed.Errs.line_crossed', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=332,
)

_LINECROSSED_SIGNALS = _descriptor.Descriptor(
  name='Signals',
  full_name='pb.Carla.LineCrossed.Signals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_crossed', full_name='pb.Carla.LineCrossed.Signals.line_crossed', index=0,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=372,
)

_LINECROSSED_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='pb.Carla.LineCrossed.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='line_crossed', full_name='pb.Carla.LineCrossed.Timestamp.line_crossed', index=0,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=407,
)

_LINECROSSED = _descriptor.Descriptor(
  name='LineCrossed',
  full_name='pb.Carla.LineCrossed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='pb.Carla.LineCrossed.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errs', full_name='pb.Carla.LineCrossed.errs', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signals', full_name='pb.Carla.LineCrossed.signals', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='pb.Carla.LineCrossed.timestamps', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LINECROSSED_ERRS, _LINECROSSED_SIGNALS, _LINECROSSED_TIMESTAMP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=407,
)

_LINECROSSED_ERRS.fields_by_name['line_crossed'].enum_type = SensorNearData_dot_SensorStates__pb2._SENSORSTATES
_LINECROSSED_ERRS.containing_type = _LINECROSSED
_LINECROSSED_SIGNALS.containing_type = _LINECROSSED
_LINECROSSED_TIMESTAMP.containing_type = _LINECROSSED
_LINECROSSED.fields_by_name['header'].message_type = header__pb2._HEADER
_LINECROSSED.fields_by_name['errs'].message_type = _LINECROSSED_ERRS
_LINECROSSED.fields_by_name['signals'].message_type = _LINECROSSED_SIGNALS
_LINECROSSED.fields_by_name['timestamps'].message_type = _LINECROSSED_TIMESTAMP
DESCRIPTOR.message_types_by_name['LineCrossed'] = _LINECROSSED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LineCrossed = _reflection.GeneratedProtocolMessageType('LineCrossed', (_message.Message,), {

  'Errs' : _reflection.GeneratedProtocolMessageType('Errs', (_message.Message,), {
    'DESCRIPTOR' : _LINECROSSED_ERRS,
    '__module__' : 'Carla.LineCrossed_pb2'
    # @@protoc_insertion_point(class_scope:pb.Carla.LineCrossed.Errs)
    })
  ,

  'Signals' : _reflection.GeneratedProtocolMessageType('Signals', (_message.Message,), {
    'DESCRIPTOR' : _LINECROSSED_SIGNALS,
    '__module__' : 'Carla.LineCrossed_pb2'
    # @@protoc_insertion_point(class_scope:pb.Carla.LineCrossed.Signals)
    })
  ,

  'Timestamp' : _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
    'DESCRIPTOR' : _LINECROSSED_TIMESTAMP,
    '__module__' : 'Carla.LineCrossed_pb2'
    # @@protoc_insertion_point(class_scope:pb.Carla.LineCrossed.Timestamp)
    })
  ,
  'DESCRIPTOR' : _LINECROSSED,
  '__module__' : 'Carla.LineCrossed_pb2'
  # @@protoc_insertion_point(class_scope:pb.Carla.LineCrossed)
  })
_sym_db.RegisterMessage(LineCrossed)
_sym_db.RegisterMessage(LineCrossed.Errs)
_sym_db.RegisterMessage(LineCrossed.Signals)
_sym_db.RegisterMessage(LineCrossed.Timestamp)


# @@protoc_insertion_point(module_scope)
